[package]
name = "deno_doc"
version = "0.1.0"
authors = ["Bartek Iwańczuk <biwanczuk@gmail.com>"]
edition = "2018"

[dependencies]
swc_ecma_parser = "0.19"
swc_ecma_ast = "0.17"
swc_common = "0.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
regex = "1"